### ISSUE TITLE
Вопрос по node_modules

### ISSUE THREAD

**Issue by jefo** [WB-Tecnologies/foo-project#11]
@dizballanze yarn кеширует модули в локальном репе, можно ли этот репо добавить в бокс вагранта? что бы быстрее разворачивать командой yarn install . но нужно учесть что версии могут обновляться

**Comment by dizballanze** [comment]
не думаю что это хорошая идея, все что относительно часто меняется мы не выносим в базовый бокс, в том числе зависимости фронтенда и бека
