### ISSUE TITLE
Нужно бандлить vendors и js текущей страницы и грузить их async

### ISSUE THREAD

**Issue by psr1919plus21** [WB-Tecnologies/foo-project#8]

**Comment by jefo** [comment]
не думаю что async хорошая идея, потому что важен порядок загрузки: сначала нужно дождаться загрузки вендорных скриптов, потом запускать наш
```html
<script async src="/static/vendor.js"></script> 
<script async src="/static/page.js"></script>
```
в примере `page.js` может загрузиться раньше `vendor.js`. поэтому предлагаю по классике вставлять перед закрывающим `</body>`

**Comment by psr1919plus21** [comment]
Да, вместо `async` можно использовать `defer`, скрипты по прежнему будут грузиться асинхронно, но порядок их запуска будет гарантирован.
Если их сбандлить в один файл, то и `async` отлично подойдет.
Это не заблокирует событие `ready` и можно будет подгрузить и выполнить какой-нибудь критичный легковесный скриптик.

**Comment by psr1919plus21** [comment]
Наверное `defer` даже предпочтительнее потому, потому что страницы к странице зависимости могут различаться и лучше иметь один лишний запрос, но при этом иметь возможность легко менять вендоры. Так более гибко получится.
